# Generated by Django 4.0.6 on 2022-08-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('filename', models.CharField(max_length=256)),
                ('mimetype', models.CharField(blank=True, choices=[('aac', 'audio/aac'), ('x-abiword', 'application/x-abiword'), ('x-freearc', 'application/x-freearc'), ('avif', 'image/avif'), ('x-msvideo', 'video/x-msvideo'), ('vnd.amazon.ebook', 'application/vnd.amazon.ebook'), ('octet-stream', 'application/octet-stream'), ('bmp', 'image/bmp'), ('x-bzip', 'application/x-bzip'), ('x-bzip2', 'application/x-bzip2'), ('x-cdf', 'application/x-cdf'), ('x-csh', 'application/x-csh'), ('css', 'text/css'), ('csv', 'text/csv'), ('msword', 'application/msword'), ('vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'), ('vnd.ms-fontobject', 'application/vnd.ms-fontobject'), ('epub+zip', 'application/epub+zip'), ('gzip', 'application/gzip'), ('gif', 'image/gif'), ('html', 'text/html'), ('vnd.microsoft.icon', 'image/vnd.microsoft.icon'), ('calendar', 'text/calendar'), ('java-archive', 'application/java-archive'), ('jpeg', 'image/jpeg'), ('javascript', 'text/javascript'), ('json', 'application/json'), ('ld+json', 'application/ld+json'), ('midi audio', 'audio/midi audio/x-midi'), ('javascript', 'text/javascript'), ('mpeg', 'audio/mpeg'), ('mp4', 'video/mp4'), ('mpeg', 'video/mpeg'), ('vnd.apple.installer+xml', 'application/vnd.apple.installer+xml'), ('vnd.oasis.opendocument.presentation', 'application/vnd.oasis.opendocument.presentation'), ('vnd.oasis.opendocument.spreadsheet', 'application/vnd.oasis.opendocument.spreadsheet'), ('vnd.oasis.opendocument.text', 'application/vnd.oasis.opendocument.text'), ('ogg', 'audio/ogg'), ('ogg', 'video/ogg'), ('ogg', 'application/ogg'), ('opus', 'audio/opus'), ('otf', 'font/otf'), ('png', 'image/png'), ('pdf', 'application/pdf'), ('x-httpd-php', 'application/x-httpd-php'), ('vnd.ms-powerpoint', 'application/vnd.ms-powerpoint'), ('vnd.openxmlformats-officedocument.presentationml.presentation', 'application/vnd.openxmlformats-officedocument.presentationml.presentation'), ('vnd.rar', 'application/vnd.rar'), ('rtf', 'application/rtf'), ('x-sh', 'application/x-sh'), ('svg+xml', 'image/svg+xml'), ('x-shockwave-flash', 'application/x-shockwave-flash'), ('x-tar', 'application/x-tar'), ('tiff', 'image/tiff'), ('mp2t', 'video/mp2t'), ('ttf', 'font/ttf'), ('plain', 'text/plain'), ('vnd.visio', 'application/vnd.visio'), ('wav', 'audio/wav'), ('webm', 'audio/webm'), ('webm', 'video/webm'), ('webp', 'image/webp'), ('woff', 'font/woff'), ('woff2', 'font/woff2'), ('xhtml+xml', 'application/xhtml+xml'), ('vnd.ms-excel', 'application/vnd.ms-excel'), ('vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'), ('xml', 'application/xml'), ('xml', 'text/xml'), ('atom+xml', 'application/atom+xml'), ('vnd.mozilla.xul+xml', 'application/vnd.mozilla.xul+xml'), ('zip', 'application/zip'), ('3gpp', 'video/3gpp'), ('3gpp', 'audio/3gpp'), ('3gpp2', 'video/3gpp2'), ('3gpp2', 'audio/3gpp2'), ('x-7z-compressed', 'application/x-7z-compressed')], max_length=256, null=True)),
                ('path', models.FilePathField(blank=True, null=True)),
            ],
        ),
    ]
